# Zone config for neck_double_breasted+buttons_6+lapel_wide+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_6_LAPEL_WIDE_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(227, 119), (198, 136), (200, 154), (209, 169), (221, 184), (243, 215), (260, 245), (284, 275), (293, 287), (305, 256), (305, 220), (289, 184), (276, 139), (267, 104), (260, 78), (262, 58), (248, 74), (230, 93), (215, 105), (229, 122)],
        "rotation": -26.0,
    },
    {
        "polygon": [(272, 357), (296, 332), (314, 311), (332, 293), (344, 274), (363, 248), (383, 219), (398, 192), (416, 163), (424, 139), (397, 117), (414, 115), (404, 105), (399, 93), (389, 79), (373, 64), (363, 55), (366, 75), (357, 108), (343, 146), (330, 188), (313, 229), (300, 273), (292, 292), (278, 322), (270, 352)],
        "rotation": 32.0,
    },
]
