# Zone config for neck_single_breasted+buttons_2+lapel_wide+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_2_LAPEL_WIDE_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(228, 121), (199, 134), (213, 169), (235, 217), (252, 252), (274, 292), (296, 331), (308, 349), (310, 332), (311, 324), (309, 308), (296, 266), (285, 222), (275, 177), (268, 134), (259, 105), (255, 88), (257, 71), (260, 62), (241, 77), (221, 98), (214, 107), (230, 120)],
        "rotation": -25.0,
    },
    {
        "polygon": [(305, 376), (323, 343), (343, 307), (365, 266), (390, 214), (412, 165), (425, 137), (404, 122), (399, 119), (417, 114), (397, 96), (387, 81), (369, 57), (368, 77), (363, 103), (354, 147), (342, 198), (333, 248), (322, 286), (315, 324), (303, 374)],
        "rotation": 25.0,
    },
]
