# Zone config for neck_single_breasted+buttons_1+lapel_narrow+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_1_LAPEL_NARROW_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(262, 58), (256, 80), (258, 104), (268, 134), (275, 184), (283, 232), (293, 268), (303, 317), (308, 330), (306, 370), (294, 338), (279, 313), (265, 278), (251, 245), (241, 211), (233, 190), (231, 164), (225, 131), (226, 104), (229, 91), (248, 78), (261, 61)],
        "rotation": -20.0,
    },
    {
        "polygon": [(303, 397), (321, 359), (346, 314), (357, 281), (369, 245), (379, 220), (388, 188), (393, 163), (394, 137), (398, 113), (394, 95), (369, 60), (368, 81), (360, 113), (347, 177), (335, 241), (324, 284), (316, 327), (301, 396)],
        "rotation": 20.0,
    },
]
