# Zone config for neck_double_breasted+buttons_2+lapel_wide+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_2_LAPEL_WIDE_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(228, 121), (212, 108), (225, 94), (241, 84), (259, 63), (260, 82), (267, 108), (274, 140), (277, 167), (285, 196), (293, 230), (302, 262), (308, 277), (305, 305), (299, 325), (293, 345), (277, 312), (261, 280), (247, 252), (237, 229), (220, 193), (200, 137), (227, 120)],
        "rotation": -22.0,
    },
    {
        "polygon": [(267, 418), (288, 395), (313, 361), (331, 330), (355, 291), (374, 256), (389, 221), (400, 192), (412, 164), (423, 136), (396, 119), (415, 115), (400, 89), (387, 83), (367, 53), (365, 77), (352, 126), (339, 173), (329, 225), (318, 267), (309, 297), (284, 364), (270, 411)],
        "rotation": 22.0,
    },
]
