# Zone config for neck_double_breasted+buttons_4+lapel_narrow+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_NARROW_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(260, 62), (248, 71), (237, 85), (231, 92), (230, 107), (225, 135), (231, 162), (236, 180), (253, 211), (277, 252), (290, 280), (293, 288), (309, 248), (296, 205), (281, 156), (271, 120), (261, 91), (260, 77), (262, 60)],
        "rotation": -27.0,
    },
    {
        "polygon": [(272, 351), (293, 327), (319, 295), (345, 253), (362, 216), (386, 173), (393, 141), (396, 107), (395, 89), (366, 56), (363, 76), (357, 106), (343, 146), (332, 179), (325, 206), (317, 236), (299, 266), (288, 307), (271, 347)],
        "rotation": 25.0,
    },
]
