# Zone config for neck_single_breasted+buttons_1+lapel_wide+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_1_LAPEL_WIDE_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(261, 59), (249, 74), (235, 87), (220, 102), (214, 108), (227, 121), (197, 138), (226, 208), (253, 258), (271, 301), (291, 343), (307, 363), (309, 344), (306, 323), (299, 302), (293, 267), (283, 223), (275, 192), (271, 157), (267, 125), (261, 101), (257, 82), (261, 59)],
        "rotation": -23.0,
    },
    {
        "polygon": [(307, 385), (323, 352), (346, 321), (360, 281), (375, 251), (399, 195), (423, 142), (395, 120), (415, 116), (400, 90), (387, 82), (377, 68), (366, 57), (366, 80), (359, 119), (351, 161), (339, 219), (323, 285), (312, 332), (307, 383)],
        "rotation": 24.0,
    },
]
