# Zone config for neck_single_breasted+buttons_1+lapel_medium+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_1_LAPEL_MEDIUM_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(214, 115), (217, 102), (224, 94), (241, 83), (259, 63), (263, 58), (257, 85), (264, 121), (282, 214), (295, 274), (307, 320), (310, 342), (310, 367), (294, 339), (277, 302), (257, 259), (229, 202), (196, 108), (213, 114)],
        "rotation": -22.0,
    },
    {
        "polygon": [(303, 398), (327, 353), (345, 307), (369, 259), (392, 200), (410, 155), (430, 107), (409, 109), (401, 94), (388, 84), (378, 69), (365, 56), (366, 78), (361, 110), (352, 145), (346, 182), (337, 235), (324, 284), (314, 334), (299, 393), (303, 401)],
        "rotation": 22.0,
    },
]
