# Zone config for neck_single_breasted+buttons_1+lapel_medium+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_1_LAPEL_MEDIUM_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(232, 119), (206, 135), (241, 221), (269, 291), (303, 361), (311, 342), (305, 317), (293, 266), (282, 209), (272, 166), (266, 124), (259, 93), (260, 60), (244, 79), (221, 101), (215, 108), (230, 118)],
        "rotation": -20.0,
    },
    {
        "polygon": [(304, 396), (323, 356), (346, 314), (364, 270), (381, 230), (393, 198), (405, 167), (420, 136), (395, 119), (413, 117), (403, 91), (386, 82), (366, 56), (366, 73), (365, 91), (364, 115), (358, 131), (347, 175), (342, 212), (327, 274), (320, 322), (305, 359), (301, 390)],
        "rotation": 20.0,
    },
]
