# Zone config for neck_double_breasted+buttons_4+lapel_medium+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_MEDIUM_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(294, 288), (309, 252), (294, 199), (279, 153), (267, 105), (259, 77), (260, 61), (245, 80), (225, 95), (213, 108), (231, 119), (208, 131), (222, 164), (233, 184), (243, 202), (262, 233), (293, 287)],
        "rotation": -23.0,
    },
    {
        "polygon": [(274, 352), (290, 333), (310, 311), (334, 279), (361, 234), (384, 196), (402, 166), (418, 140), (393, 117), (413, 116), (402, 93), (396, 87), (388, 82), (366, 55), (366, 72), (363, 89), (346, 136), (326, 202), (312, 239), (293, 297), (275, 334), (273, 350)],
        "rotation": 22.0,
    },
]
