# Zone config for neck_single_breasted+buttons_2+lapel_medium+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_2_LAPEL_MEDIUM_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(230, 120), (207, 130), (232, 192), (257, 252), (289, 320), (306, 349), (311, 326), (307, 296), (294, 257), (283, 216), (275, 181), (270, 153), (263, 125), (259, 100), (259, 80), (260, 61), (244, 79), (230, 92), (216, 107), (232, 124)],
        "rotation": -20.0,
    },
    {
        "polygon": [(304, 371), (331, 328), (359, 273), (376, 231), (395, 188), (419, 141), (394, 117), (408, 115), (413, 115), (405, 102), (399, 94), (387, 84), (366, 56), (366, 78), (355, 130), (347, 170), (339, 220), (326, 264), (316, 306), (304, 370)],
        "rotation": 20.0,
    },
]
