# Zone config for neck_single_breasted+buttons_2+lapel_narrow+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_2_LAPEL_NARROW_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(237, 118), (216, 125), (221, 158), (238, 197), (263, 250), (285, 304), (303, 345), (314, 323), (303, 291), (292, 245), (282, 203), (274, 163), (266, 129), (258, 100), (257, 76), (261, 60), (244, 81), (224, 99), (218, 105), (234, 118)],
        "rotation": -22.0,
    },
    {
        "polygon": [(303, 378), (320, 349), (336, 321), (355, 270), (375, 228), (389, 188), (412, 131), (389, 117), (406, 114), (400, 100), (395, 91), (386, 84), (377, 70), (367, 57), (366, 79), (359, 116), (348, 160), (337, 219), (332, 250), (322, 284), (318, 306), (305, 345), (300, 380)],
        "rotation": 23.0,
    },
]
