# Zone config for neck_double_breasted+buttons_4+lapel_medium+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_MEDIUM_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(261, 60), (261, 71), (263, 88), (267, 104), (275, 125), (305, 228), (306, 255), (294, 286), (270, 252), (245, 214), (231, 183), (223, 153), (221, 112), (226, 93), (260, 60)],
        "rotation": -22.0,
    },
    {
        "polygon": [(272, 351), (302, 315), (332, 279), (357, 244), (379, 205), (399, 158), (399, 125), (399, 99), (387, 80), (367, 58), (363, 83), (354, 113), (343, 158), (320, 214), (309, 255), (301, 274), (288, 306), (270, 350)],
        "rotation": 22.0,
    },
]
