# Zone config for neck_single_breasted+buttons_3+lapel_wide+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_3_LAPEL_WIDE_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(229, 119), (200, 136), (237, 199), (270, 238), (300, 274), (304, 279), (310, 260), (303, 241), (286, 194), (277, 158), (267, 129), (257, 102), (257, 83), (259, 65), (243, 78), (226, 96), (214, 108), (227, 118)],
        "rotation": -36.0,
    },
    {
        "polygon": [(304, 309), (316, 279), (346, 243), (371, 218), (394, 189), (415, 158), (422, 137), (397, 117), (413, 115), (406, 101), (398, 92), (392, 91), (387, 82), (376, 68), (367, 55), (369, 85), (359, 117), (345, 160), (333, 205), (319, 247), (303, 288), (303, 303)],
        "rotation": 36.0,
    },
]
