# Zone config for neck_mao.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_MAO = [
    {
        "polygon": [(250, 72), (253, 77), (253, 80), (259, 87), (270, 97), (285, 105), (298, 107), (300, 88), (294, 79), (277, 74), (265, 63), (259, 49), (249, 70)],
        "rotation": 16.0,
    },
    {
        "polygon": [(321, 111), (322, 90), (332, 80), (350, 71), (361, 61), (366, 50), (361, 41), (375, 65), (374, 77), (371, 87), (361, 95), (348, 105), (335, 105), (325, 109)],
        "rotation": -16.0,
    },
]
