# Zone config for neck_double_breasted+buttons_4+lapel_wide+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_WIDE_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(229, 117), (200, 138), (219, 183), (267, 252), (289, 279), (293, 287), (307, 254), (301, 217), (289, 180), (271, 118), (261, 83), (261, 60), (248, 75), (233, 92), (214, 107), (227, 115)],
        "rotation": -33.0,
    },
    {
        "polygon": [(274, 354), (298, 319), (326, 294), (350, 261), (381, 218), (402, 182), (424, 141), (397, 118), (416, 112), (403, 92), (388, 84), (367, 54), (362, 86), (352, 131), (340, 158), (326, 189), (316, 222), (306, 264), (270, 348), (274, 353)],
        "rotation": 33.0,
    },
]
