# Zone config for neck_double_breasted+buttons_6+lapel_narrow+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_6_LAPEL_NARROW_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(258, 61), (258, 81), (260, 95), (267, 115), (287, 171), (299, 211), (307, 235), (308, 255), (293, 287), (282, 262), (262, 229), (251, 203), (232, 176), (221, 150), (212, 127), (236, 116), (216, 102), (230, 90), (243, 80), (258, 64)],
        "rotation": -28.0,
    },
    {
        "polygon": [(281, 343), (266, 357), (275, 335), (289, 304), (301, 277), (311, 247), (319, 221), (332, 185), (344, 154), (350, 126), (359, 101), (365, 77), (365, 56), (387, 80), (407, 111), (390, 116), (409, 129), (405, 149), (389, 175), (370, 208), (335, 268), (317, 295), (299, 324), (285, 342), (282, 341)],
        "rotation": 32.0,
    },
]
