# Zone config for neck_double_breasted+buttons_4+lapel_narrow+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_NARROW_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(213, 125), (235, 116), (218, 103), (233, 86), (260, 62), (262, 94), (272, 119), (282, 154), (306, 241), (295, 287), (281, 254), (263, 223), (249, 195), (230, 164), (213, 125)],
        "rotation": -26.0,
    },
    {
        "polygon": [(270, 353), (293, 333), (327, 277), (361, 222), (393, 168), (411, 130), (389, 115), (407, 112), (401, 88), (389, 84), (364, 54), (366, 77), (358, 102), (347, 141), (329, 190), (314, 236), (298, 276), (283, 317), (268, 353)],
        "rotation": 28.0,
    },
]
