# Zone config for neck_double_breasted+buttons_6+lapel_narrow+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_6_LAPEL_NARROW_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(226, 116), (236, 90), (247, 77), (261, 58), (261, 80), (267, 107), (286, 170), (301, 212), (307, 233), (307, 242), (298, 282), (295, 286), (279, 265), (258, 217), (233, 171), (221, 134), (210, 109), (228, 117)],
        "rotation": -24.0,
    },
    {
        "polygon": [(270, 354), (295, 328), (322, 296), (340, 257), (359, 220), (381, 183), (397, 140), (415, 112), (393, 114), (393, 91), (376, 70), (368, 57), (366, 87), (348, 137), (327, 193), (314, 231), (300, 269), (282, 316), (266, 357)],
        "rotation": 26.0,
    },
]
