# Zone config for neck_double_breasted+buttons_6+lapel_narrow+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_6_LAPEL_NARROW_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(234, 85), (227, 99), (227, 114), (227, 137), (227, 156), (236, 173), (252, 210), (270, 242), (289, 276), (291, 288), (307, 249), (304, 225), (296, 196), (285, 161), (276, 135), (268, 113), (263, 91), (261, 57), (245, 78), (236, 83)],
        "rotation": -24.0,
    },
    {
        "polygon": [(273, 352), (284, 342), (290, 334), (305, 318), (319, 290), (332, 269), (349, 241), (363, 220), (376, 195), (382, 179), (390, 160), (397, 124), (395, 99), (388, 84), (366, 55), (365, 70), (362, 92), (352, 127), (336, 177), (321, 216), (309, 246), (300, 273), (292, 293), (282, 323), (267, 350)],
        "rotation": 29.0,
    },
]
