# Zone config for neck_double_breasted+buttons_4+lapel_narrow+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_NARROW_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(213, 110), (240, 186), (263, 225), (282, 261), (291, 283), (306, 257), (303, 224), (286, 171), (278, 137), (269, 105), (261, 81), (260, 59), (245, 77), (236, 90), (229, 113), (214, 110)],
        "rotation": -26.0,
    },
    {
        "polygon": [(274, 353), (318, 297), (344, 250), (367, 213), (380, 179), (396, 141), (415, 110), (395, 111), (393, 87), (365, 56), (364, 82), (353, 110), (338, 158), (328, 197), (315, 231), (304, 261), (292, 294), (273, 348)],
        "rotation": 28.0,
    },
]
