# Zone config for pleats_single.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_PLEATS_SINGLE = [
    {
        "polygon": [(331, 57), (330, 101), (518, 97), (521, 57), (332, 57)],
        "rotation": 90.0,
    },
    {
        "polygon": [(520, 99), (542, 96), (542, 59), (522, 59), (519, 98)],
        "rotation": 4.0,
    },
]
