# Zone config for neck_double_breasted+buttons_6+lapel_medium+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_6_LAPEL_MEDIUM_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(221, 118), (232, 93), (242, 81), (263, 60), (261, 84), (278, 140), (291, 195), (305, 233), (308, 244), (292, 283), (267, 244), (243, 204), (227, 170), (206, 111), (220, 117)],
        "rotation": -27.0,
    },
    {
        "polygon": [(270, 355), (299, 323), (327, 283), (361, 228), (392, 170), (408, 139), (419, 115), (402, 116), (393, 95), (383, 81), (374, 70), (366, 55), (364, 83), (354, 123), (332, 186), (320, 220), (304, 264), (289, 304), (274, 334), (269, 354)],
        "rotation": 28.0,
    },
]
