# Zone config for neck_single_breasted+buttons_1+lapel_medium+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_1_LAPEL_MEDIUM_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(215, 116), (193, 107), (231, 206), (267, 289), (296, 348), (304, 363), (309, 343), (300, 301), (288, 243), (278, 189), (266, 132), (259, 86), (261, 58), (240, 82), (220, 101), (215, 116)],
        "rotation": -23.0,
    },
    {
        "polygon": [(303, 397), (336, 333), (381, 228), (419, 130), (431, 105), (411, 111), (400, 96), (384, 80), (367, 56), (366, 90), (353, 153), (333, 248), (317, 319), (301, 380), (301, 395)],
        "rotation": 24.0,
    },
]
