# Zone config for neck_single_breasted+buttons_1+lapel_narrow+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_1_LAPEL_NARROW_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(235, 116), (214, 125), (236, 185), (260, 250), (283, 313), (307, 366), (308, 342), (300, 305), (280, 215), (268, 142), (260, 104), (256, 82), (262, 60), (242, 84), (222, 103), (238, 118)],
        "rotation": -20.0,
    },
    {
        "polygon": [(300, 402), (330, 337), (365, 253), (397, 167), (410, 130), (392, 117), (405, 112), (400, 95), (389, 87), (379, 74), (367, 57), (366, 78), (360, 121), (349, 165), (338, 231), (328, 278), (320, 316), (308, 350), (304, 388)],
        "rotation": 20.0,
    },
]
