# Zone config for neck_single_breasted+buttons_3+lapel_narrow+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_3_LAPEL_NARROW_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(217, 111), (200, 103), (216, 149), (247, 196), (283, 250), (304, 279), (307, 258), (294, 219), (281, 171), (269, 129), (259, 98), (259, 76), (260, 58), (246, 77), (232, 89), (222, 99), (217, 111)],
        "rotation": -32.0,
    },
    {
        "polygon": [(305, 298), (340, 251), (366, 208), (401, 156), (419, 114), (424, 99), (406, 107), (401, 94), (389, 83), (377, 69), (366, 56), (370, 82), (360, 111), (335, 190), (329, 214), (320, 238), (314, 263), (303, 291), (305, 295)],
        "rotation": 31.0,
    },
]
