# Zone config for neck_double_breasted+buttons_2+lapel_medium+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_2_LAPEL_MEDIUM_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(221, 117), (232, 92), (242, 78), (258, 63), (259, 88), (273, 138), (291, 215), (304, 268), (307, 292), (294, 343), (263, 280), (241, 233), (226, 183), (206, 109), (224, 119)],
        "rotation": -24.0,
    },
    {
        "polygon": [(270, 420), (316, 366), (353, 290), (384, 210), (405, 150), (421, 114), (401, 117), (394, 94), (384, 80), (364, 54), (366, 77), (359, 101), (351, 131), (337, 192), (325, 240), (312, 283), (301, 320), (272, 415)],
        "rotation": 21.0,
    },
]
