# Zone config for neck_single_breasted+buttons_2+lapel_narrow+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_2_LAPEL_NARROW_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(218, 112), (199, 104), (215, 149), (238, 196), (259, 240), (279, 286), (297, 326), (308, 345), (310, 323), (299, 282), (287, 229), (276, 181), (268, 133), (259, 100), (257, 77), (263, 59), (234, 85), (221, 102), (218, 113)],
        "rotation": -23.0,
    },
    {
        "polygon": [(306, 374), (332, 319), (358, 257), (382, 197), (400, 154), (424, 101), (402, 108), (395, 91), (379, 74), (366, 56), (367, 73), (359, 110), (350, 164), (336, 221), (326, 272), (315, 314), (306, 370)],
        "rotation": 21.0,
    },
]
