# Zone config for neck_double_breasted+buttons_2+lapel_wide+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_2_LAPEL_WIDE_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(228, 121), (199, 135), (237, 235), (265, 298), (292, 343), (305, 308), (297, 251), (278, 162), (263, 94), (258, 76), (263, 61), (214, 106), (225, 121)],
        "rotation": -26.0,
    },
    {
        "polygon": [(269, 419), (306, 374), (348, 302), (385, 228), (422, 139), (397, 123), (416, 115), (399, 91), (385, 84), (376, 70), (365, 55), (365, 86), (340, 184), (317, 263), (300, 321), (281, 377), (270, 416)],
        "rotation": 26.0,
    },
]
