# Zone config for neck_double_breasted+buttons_6+lapel_wide+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_6_LAPEL_WIDE_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(219, 126), (193, 117), (202, 151), (214, 179), (236, 215), (258, 243), (277, 267), (291, 284), (307, 249), (299, 216), (289, 180), (277, 138), (266, 106), (257, 80), (262, 59), (243, 76), (227, 105), (216, 124)],
        "rotation": -34.0,
    },
    {
        "polygon": [(270, 354), (304, 317), (340, 277), (373, 231), (401, 184), (415, 156), (428, 117), (410, 121), (395, 98), (382, 78), (365, 56), (365, 75), (355, 111), (340, 154), (323, 203), (308, 252), (294, 287), (281, 326), (270, 351)],
        "rotation": 30.0,
    },
]
