# Zone config for neck_single_breasted+buttons_2+lapel_medium+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_2_LAPEL_MEDIUM_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(275, 163), (291, 244), (305, 297), (311, 317), (309, 351), (266, 279), (239, 221), (227, 170), (219, 132), (221, 105), (225, 92), (237, 85), (249, 76), (261, 59), (257, 85), (265, 126), (276, 163)],
        "rotation": -22.0,
    },
    {
        "polygon": [(316, 354), (350, 296), (376, 245), (394, 181), (401, 140), (397, 106), (389, 83), (364, 56), (370, 78), (353, 138), (335, 231), (326, 267), (318, 298), (314, 323), (308, 346), (302, 371), (318, 353)],
        "rotation": 22.0,
    },
]
