# Zone config for neck_single_breasted+buttons_1+lapel_wide+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_1_LAPEL_WIDE_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(204, 119), (184, 112), (214, 193), (234, 233), (261, 285), (289, 334), (299, 360), (302, 370), (308, 338), (301, 300), (282, 227), (272, 164), (264, 112), (257, 87), (261, 58), (246, 79), (226, 90), (213, 107), (205, 119)],
        "rotation": -25.0,
    },
    {
        "polygon": [(303, 395), (359, 290), (390, 231), (415, 168), (435, 111), (417, 116), (405, 98), (392, 86), (366, 58), (368, 74), (358, 119), (349, 169), (333, 251), (323, 288), (313, 332), (307, 364), (304, 386)],
        "rotation": 25.0,
    },
]
