# Zone config for neck_double_breasted+buttons_4+lapel_medium+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_MEDIUM_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(229, 119), (205, 133), (231, 190), (256, 232), (295, 288), (307, 250), (295, 203), (280, 156), (265, 112), (257, 77), (263, 61), (213, 106), (225, 121)],
        "rotation": -28.0,
    },
    {
        "polygon": [(269, 356), (302, 321), (342, 262), (376, 202), (415, 141), (394, 119), (412, 114), (385, 83), (366, 56), (365, 77), (357, 105), (341, 153), (323, 206), (307, 252), (291, 294), (275, 338), (269, 352)],
        "rotation": 33.0,
    },
]
