# Zone config for neck_single_breasted+buttons_3+lapel_wide+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_3_LAPEL_WIDE_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(208, 120), (185, 111), (190, 140), (227, 190), (260, 229), (289, 261), (307, 281), (309, 263), (298, 231), (280, 175), (268, 126), (258, 90), (261, 58), (241, 83), (222, 98), (208, 115)],
        "rotation": -32.0,
    },
    {
        "polygon": [(311, 291), (333, 258), (363, 229), (397, 188), (428, 137), (439, 105), (416, 113), (403, 95), (390, 86), (377, 71), (366, 55), (366, 73), (363, 100), (348, 159), (331, 211), (320, 242), (307, 274), (308, 290)],
        "rotation": 33.0,
    },
]
