# Zone config for neck_double_breasted+buttons_6+lapel_wide+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_6_LAPEL_WIDE_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(261, 62), (261, 74), (261, 92), (280, 150), (292, 189), (302, 230), (304, 248), (295, 283), (252, 237), (226, 197), (215, 161), (211, 129), (218, 106), (227, 91), (242, 80), (257, 63)],
        "rotation": -28.0,
    },
    {
        "polygon": [(263, 363), (299, 326), (338, 278), (380, 224), (395, 190), (408, 151), (402, 113), (388, 87), (372, 64), (365, 55), (367, 74), (359, 105), (321, 215), (273, 345), (263, 362)],
        "rotation": 28.0,
    },
]
