# Zone config for neck_double_breasted+buttons_4+lapel_wide+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_WIDE_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(230, 119), (197, 136), (222, 191), (237, 212), (264, 251), (289, 281), (294, 289), (305, 251), (301, 217), (284, 167), (269, 111), (258, 83), (261, 60), (249, 70), (237, 87), (216, 105), (213, 108), (228, 118)],
        "rotation": -31.0,
    },
    {
        "polygon": [(269, 357), (301, 316), (334, 282), (368, 238), (398, 190), (424, 139), (396, 117), (414, 116), (404, 99), (393, 86), (384, 79), (374, 66), (365, 55), (367, 77), (358, 101), (350, 130), (339, 160), (327, 195), (319, 220), (312, 243), (299, 275), (286, 308), (276, 337), (270, 354)],
        "rotation": 30.0,
    },
]
