# Zone config for neck_double_breasted+buttons_4+lapel_medium+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_MEDIUM_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(262, 60), (259, 80), (268, 110), (283, 164), (293, 198), (305, 230), (306, 249), (293, 286), (264, 240), (239, 202), (227, 172), (219, 138), (220, 116), (227, 95), (235, 84), (243, 81), (261, 63)],
        "rotation": -31.0,
    },
    {
        "polygon": [(273, 345), (290, 299), (308, 256), (323, 210), (338, 163), (351, 120), (362, 93), (366, 78), (367, 55), (379, 75), (394, 102), (399, 139), (394, 165), (379, 200), (365, 228), (339, 269), (320, 297), (297, 326), (276, 349), (272, 345)],
        "rotation": 30.0,
    },
]
