# Zone config for neck_double_breasted+buttons_4+lapel_wide+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_WIDE_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(218, 125), (226, 97), (240, 79), (259, 60), (260, 83), (280, 154), (300, 218), (308, 238), (295, 285), (266, 255), (241, 220), (222, 191), (209, 163), (195, 121), (222, 125)],
        "rotation": -29.0,
    },
    {
        "polygon": [(272, 349), (307, 314), (334, 282), (359, 247), (394, 197), (418, 152), (429, 117), (407, 122), (399, 102), (389, 87), (377, 70), (366, 55), (364, 81), (351, 126), (336, 169), (324, 208), (308, 249), (291, 294), (277, 328), (272, 349)],
        "rotation": 32.0,
    },
]
