# Zone config for neck_single_breasted+buttons_2+lapel_wide+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_2_LAPEL_WIDE_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(262, 61), (253, 71), (244, 79), (229, 92), (218, 107), (214, 133), (215, 155), (225, 192), (233, 218), (250, 254), (267, 289), (287, 320), (304, 341), (313, 319), (294, 256), (282, 203), (270, 147), (262, 113), (257, 91), (266, 58)],
        "rotation": -20.0,
    },
    {
        "polygon": [(307, 372), (332, 329), (354, 292), (379, 254), (395, 211), (407, 171), (406, 133), (401, 101), (385, 81), (366, 56), (367, 83), (360, 111), (353, 144), (342, 198), (334, 235), (326, 267), (321, 294), (317, 314), (311, 338), (305, 371)],
        "rotation": 20.0,
    },
]
