# Zone config for neck_double_breasted+buttons_6+lapel_wide+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_6_LAPEL_WIDE_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(227, 123), (199, 138), (227, 197), (249, 233), (270, 261), (292, 282), (303, 251), (300, 221), (290, 185), (274, 136), (263, 99), (259, 79), (262, 59), (247, 75), (226, 91), (210, 104), (225, 121)],
        "rotation": -31.0,
    },
    {
        "polygon": [(272, 356), (330, 292), (373, 228), (411, 169), (423, 139), (395, 119), (416, 115), (391, 87), (380, 72), (366, 56), (364, 85), (341, 158), (322, 215), (301, 267), (289, 300), (280, 331), (270, 355)],
        "rotation": 29.0,
    },
]
