# Zone config for neck_single_breasted+buttons_3+lapel_wide+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_3_LAPEL_WIDE_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(228, 121), (199, 136), (222, 180), (256, 225), (280, 252), (302, 281), (312, 256), (291, 205), (275, 154), (264, 114), (256, 84), (262, 58), (250, 72), (232, 88), (212, 101), (207, 106), (227, 119)],
        "rotation": -33.0,
    },
    {
        "polygon": [(311, 291), (349, 244), (387, 199), (414, 159), (423, 138), (397, 121), (413, 115), (402, 98), (392, 87), (381, 78), (363, 53), (368, 72), (362, 98), (354, 131), (346, 166), (332, 211), (317, 246), (310, 288)],
        "rotation": 33.0,
    },
]
