# Zone config for neck_double_breasted+buttons_4+lapel_narrow+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_NARROW_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(233, 116), (215, 126), (237, 183), (264, 228), (287, 271), (293, 287), (308, 251), (303, 217), (291, 192), (273, 130), (262, 90), (258, 78), (261, 62), (237, 83), (219, 104), (235, 118)],
        "rotation": -31.0,
    },
    {
        "polygon": [(271, 355), (305, 315), (332, 270), (365, 213), (397, 159), (410, 129), (389, 115), (405, 113), (399, 93), (385, 80), (377, 70), (365, 55), (365, 88), (349, 129), (338, 173), (320, 222), (304, 259), (283, 315), (272, 353)],
        "rotation": 31.0,
    },
]
