# Zone config for neck_single_breasted+buttons_1+lapel_narrow+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_1_LAPEL_NARROW_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(365, 54), (367, 71), (366, 87), (361, 111), (353, 146), (346, 184), (339, 223), (330, 258), (319, 301), (314, 329), (309, 362), (301, 396), (322, 361), (347, 304), (363, 265), (381, 212), (392, 164), (396, 124), (396, 102), (390, 89), (365, 52)],
        "rotation": 20.0,
    },
    {
        "polygon": [(303, 359), (267, 291), (246, 229), (229, 164), (224, 120), (226, 98), (250, 77), (261, 58), (255, 81), (265, 120), (284, 231), (302, 299), (312, 327), (302, 363)],
        "rotation": -20.0,
    },
]
