# Zone config for neck_single_breasted+buttons_3+lapel_medium+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_3_LAPEL_MEDIUM_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(304, 277), (276, 248), (254, 220), (240, 192), (224, 154), (220, 118), (224, 97), (235, 85), (245, 76), (260, 61), (258, 90), (268, 124), (282, 181), (293, 216), (306, 245), (310, 260), (305, 276)],
        "rotation": -32.0,
    },
    {
        "polygon": [(309, 297), (328, 266), (373, 215), (395, 174), (399, 137), (398, 100), (385, 81), (364, 55), (368, 76), (356, 125), (344, 163), (332, 203), (325, 231), (312, 259), (303, 284), (310, 293)],
        "rotation": 34.0,
    },
]
