# Zone config for neck_double_breasted+buttons_2+lapel_wide+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_2_LAPEL_WIDE_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(259, 61), (236, 86), (220, 103), (214, 120), (212, 150), (217, 179), (226, 210), (245, 256), (263, 298), (281, 325), (292, 347), (304, 307), (299, 260), (288, 210), (276, 150), (264, 101), (258, 83), (259, 62)],
        "rotation": -25.0,
    },
    {
        "polygon": [(265, 421), (297, 384), (336, 322), (369, 271), (389, 226), (409, 168), (405, 126), (401, 101), (387, 86), (378, 71), (365, 56), (365, 79), (352, 133), (336, 186), (322, 251), (303, 319), (282, 366), (264, 424)],
        "rotation": 30.0,
    },
]
