# Zone config for neck_single_breasted+buttons_3+lapel_medium+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_3_LAPEL_MEDIUM_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(205, 131), (238, 184), (256, 217), (277, 246), (297, 274), (305, 281), (310, 253), (280, 175), (268, 132), (259, 103), (258, 82), (259, 60), (247, 76), (214, 106), (229, 119), (206, 132)],
        "rotation": -35.0,
    },
    {
        "polygon": [(307, 297), (350, 237), (395, 172), (418, 137), (394, 120), (412, 114), (392, 90), (380, 77), (364, 55), (367, 74), (363, 95), (347, 158), (328, 222), (315, 258), (303, 290), (306, 296)],
        "rotation": 35.0,
    },
]
