# Zone config for neck_double_breasted+buttons_6+lapel_medium+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_6_LAPEL_MEDIUM_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(230, 118), (206, 131), (228, 184), (260, 234), (295, 290), (307, 250), (295, 206), (280, 150), (266, 107), (258, 82), (260, 57), (247, 74), (215, 108), (228, 118)],
        "rotation": -30.0,
    },
    {
        "polygon": [(269, 355), (301, 321), (331, 274), (370, 219), (405, 161), (418, 134), (393, 119), (412, 114), (402, 98), (391, 90), (382, 77), (364, 57), (365, 75), (363, 97), (349, 137), (334, 181), (315, 231), (296, 286), (281, 316), (269, 353)],
        "rotation": 32.0,
    },
]
