# Zone config for neck_double_breasted+buttons_2+lapel_narrow+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_2_LAPEL_NARROW_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(261, 58), (259, 79), (266, 118), (277, 167), (294, 228), (304, 267), (306, 284), (306, 298), (293, 344), (250, 243), (237, 199), (228, 154), (226, 111), (230, 91), (241, 79), (260, 58)],
        "rotation": -22.0,
    },
    {
        "polygon": [(269, 419), (292, 396), (325, 336), (353, 288), (373, 229), (385, 180), (396, 133), (395, 104), (386, 81), (366, 55), (366, 79), (349, 139), (329, 217), (313, 277), (290, 344), (270, 411), (270, 419)],
        "rotation": 22.0,
    },
]
