# Zone config for neck_double_breasted+buttons_4+lapel_narrow+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_NARROW_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(229, 116), (204, 104), (218, 137), (239, 176), (253, 213), (266, 236), (285, 268), (293, 284), (306, 254), (304, 228), (290, 183), (275, 128), (264, 98), (259, 77), (262, 61), (245, 81), (229, 102), (226, 116)],
        "rotation": -27.0,
    },
    {
        "polygon": [(267, 356), (293, 336), (312, 304), (331, 270), (358, 225), (378, 191), (397, 146), (414, 110), (395, 115), (393, 96), (388, 83), (375, 70), (365, 56), (365, 75), (348, 128), (329, 188), (319, 222), (305, 255), (291, 292), (278, 326), (266, 355)],
        "rotation": 29.0,
    },
]
