# Zone config for neck_double_breasted+buttons_4+lapel_medium+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_MEDIUM_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(221, 119), (202, 110), (218, 147), (234, 191), (264, 237), (285, 275), (290, 286), (306, 256), (300, 214), (284, 165), (265, 101), (258, 79), (263, 61), (241, 81), (228, 105), (220, 120)],
        "rotation": -29.0,
    },
    {
        "polygon": [(269, 356), (315, 302), (348, 254), (382, 195), (407, 143), (420, 112), (402, 115), (391, 92), (373, 65), (365, 54), (364, 83), (349, 130), (330, 188), (310, 239), (295, 279), (278, 324), (268, 353)],
        "rotation": 30.0,
    },
]
