# Zone config for neck_double_breasted+buttons_4+lapel_narrow+style_lapel_round.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_4_LAPEL_NARROW_STYLE_LAPEL_ROUND = [
    {
        "polygon": [(261, 59), (261, 70), (261, 92), (268, 112), (283, 154), (292, 196), (302, 224), (306, 237), (294, 287), (270, 243), (257, 219), (244, 195), (236, 175), (228, 152), (225, 130), (227, 108), (230, 94), (236, 84), (242, 81), (258, 60)],
        "rotation": -24.0,
    },
    {
        "polygon": [(270, 353), (297, 327), (319, 292), (343, 250), (359, 218), (374, 189), (387, 161), (392, 121), (392, 97), (367, 56), (366, 80), (359, 101), (348, 137), (335, 169), (323, 209), (306, 251), (289, 297), (270, 345), (270, 352)],
        "rotation": 22.0,
    },
]
