# Zone config for neck_single_breasted+buttons_1+lapel_narrow+style_lapel_peak.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_1_LAPEL_NARROW_STYLE_LAPEL_PEAK = [
    {
        "polygon": [(217, 114), (199, 103), (221, 160), (257, 250), (280, 307), (304, 360), (309, 337), (298, 290), (282, 211), (269, 135), (258, 94), (257, 78), (261, 60), (249, 75), (230, 93), (221, 106), (218, 113)],
        "rotation": -20.0,
    },
    {
        "polygon": [(300, 402), (328, 346), (361, 269), (395, 177), (411, 130), (423, 102), (407, 110), (398, 97), (386, 85), (374, 70), (364, 53), (367, 80), (356, 135), (346, 189), (330, 262), (321, 305), (312, 330), (307, 360), (299, 400)],
        "rotation": 20.0,
    },
]
