# Zone config for neck_single_breasted+buttons_2+lapel_wide+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_SINGLE_BREASTED_BUTTONS_2_LAPEL_WIDE_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(198, 137), (298, 332), (308, 350), (310, 318), (295, 258), (285, 213), (273, 161), (266, 132), (260, 100), (257, 85), (262, 60), (241, 81), (221, 101), (212, 107), (229, 122), (198, 137)],
        "rotation": -26.0,
    },
    {
        "polygon": [(310, 367), (349, 297), (376, 244), (399, 195), (415, 160), (423, 137), (397, 118), (415, 113), (401, 95), (386, 82), (364, 54), (369, 75), (361, 110), (351, 151), (342, 194), (333, 235), (324, 279), (320, 303), (311, 325), (308, 364)],
        "rotation": 26.0,
    },
]
