# Zone config for neck_double_breasted+buttons_2+lapel_medium+style_lapel_notch.png
# Generated by tools/web_zone_picker.py
# Polygons are in ORIGINAL pixel coords (origin top-left).

ZONES_NECK_DOUBLE_BREASTED_BUTTONS_2_LAPEL_MEDIUM_STYLE_LAPEL_NOTCH = [
    {
        "polygon": [(261, 59), (261, 72), (261, 99), (272, 144), (286, 206), (299, 250), (308, 284), (291, 341), (272, 301), (251, 245), (229, 193), (207, 134), (229, 121), (212, 107), (226, 94), (240, 86), (245, 79), (256, 63), (262, 61)],
        "rotation": -23.0,
    },
    {
        "polygon": [(274, 417), (305, 377), (345, 308), (380, 224), (417, 138), (392, 122), (411, 114), (399, 96), (388, 85), (375, 70), (364, 56), (367, 77), (356, 119), (339, 187), (323, 240), (312, 279), (298, 322), (285, 365), (270, 411), (271, 413)],
        "rotation": 23.0,
    },
]
